### ISSUE TITLE
Image should have resizeMode: "cover".(Snapchat s04)(story.tsx)

### ISSUE THREAD

**Issue by PhoenixCreation** [wcandillon/can-it-be-done-in-react-native#141]
In season4 ->src ->  Snapchat -> story.tsx -> line83.

Image should have resizeMode: "cover" styling.
because it is shared element and first image(from thumbnail) has this property. so it has some fluctuation effect in android.(not tested on ios but in video I didn't noticed this.)

By adding a resizeMode: "cover" we can have better and smooth transition.

**Comment by wcandillon** [comment]
nice! Could you make a PR for it?

**Comment by PhoenixCreation** [comment]
Thank you. I have created PR. #142 
And Thanks you again for amazing content and ideas.

**Comment by PhoenixCreation** [comment]
Issue solved with PR #142 .
