### ISSUE TITLE
Rainbow charts, header doesn't refresh

### ISSUE THREAD

**Issue by nicoache1** [wcandillon/can-it-be-done-in-react-native#148]
## Description
I @wcandillon i hope you are well.
Im following your example of rainbow charts in Season 4 and I run into an issue with the refresh of the header.
Everything seems working fine because i move the cursor around the graph and the values are changing but they are not reflected in the header unless I tap in the header. ( I attach a video bellow )
I copy paste the same code that you have here in the repo and its happening the same also.

Do you have any ideas/clues of what should be the problem? I need to change things to the JS thread in order to provoke some re-render?

**EDIT:** If i add a console.log inside the `useDerivedValue` then it changes nice, but if i remove that then the issue reappears.

## Versions
``` json
 "react-native": "0.63.1",
 "react-native-redash": "16.0.6",
 "react-native-reanimated": "2.0.0-rc.1",
```

https://user-images.githubusercontent.com/26419582/104216734-37ae0880-5419-11eb-937b-34515b5761ee.mov

**Comment by orkunkarakus** [comment]
I think the system is having trouble detecting that the data variable has changed. Changing "data.percentChange" to "graphs[index.value].data.percentChange"  solves the problem.
