### ISSUE TITLE
Instagram stories not working with react-reanimated 3.0.0-rc.10

### ISSUE THREAD

**Issue by devoren** [wcandillon/can-it-be-done-in-react-native#179]
Hello! How to implement [this](https://github.com/wcandillon/can-it-be-done-in-react-native/tree/master/season1/instagram-stories) wonderful code in version 3.0? I tried to migrate but functions like abs, cond and other functions are undefined in the latest version. I don't know how to animate with worklets or use the new animation hooks. 

"react": "18.2.0",
"react-native": "0.71.1",
"react-native-reanimated": "^3.0.0-rc.10",

translationX.value is useSharedValue and comes from the parent Animated Flashlist:

        const animatedStyle = useAnimatedStyle(() => {
		const offset = index * width;
		const inputRange = [offset - width, offset + width];
		const inputOpacityRange = [offset - width, offset, offset + width];

		const translateX = interpolate(
			translationX.value,
			inputRange,
			[width / ratio, -width / ratio],
			Extrapolate.CLAMP,
		);
		const rotateY = interpolate(
			translationX.value,
			inputRange,
			[angle, -angle],
			Extrapolate.CLAMP,
		);

		const opacity = interpolate(
			translationX.value,
			inputOpacityRange,
			[0.5, 1, 0.5],
			Extrapolate.CLAMP,
		);

		const alpha = abs(rotateY);
		const gamma = sub(angle, alpha);
		const beta = sub(Math.PI, alpha, gamma);
		const w = sub(width / 2, multiply(width / 2, divide(sin(gamma), sin(beta))));
		const translateX1 = cond(greaterThan(rotateY, 0), w, multiply(w, -1));
		
		return {
			transform: [
				{ perspective },
				{ translateX },
				{ rotateY: `${w}rad` },
				{translateX: translateX1}
			],
			opacity,
		};
	});

![Screenshot_1674557862](https://user-images.githubusercontent.com/99968085/214274345-38e951fb-f397-47db-9d71-f1ff59f68e21.png)

**Comment by fukemy** [comment]
hi, did u found any solution, I want to migrate to v3 too

**Comment by fukemy** [comment]
lul I think this will make bad UX, you can look into [react native stories](https://github.com/SimformSolutionsPvtLtd/react-native-story-view), they provide cube transition work with v3

**Comment by devoren** [comment]
@fukemy I tried it then, but I have a different design and features, so I decided to make it from scratch.
