### ISSUE TITLE
horizontal-slider

### ISSUE THREAD

**Issue by Angelk90** [wcandillon/can-it-be-done-in-react-native#19]
Hi @wcandillon , I tried the project on the expo link, but it doesn't seem to work, blue screen.
Tested on android.

**Comment by wcandillon** [comment]
Guys sorry for the inconvenience 🙋🏼‍♂️

There are indeed two issues. The first one if that `ReText` doesn't work yet on Android in its current form. Then it looks like the gesture doesn't get picked up at all. I'm investigating.

**Comment by wcandillon** [comment]
I updated the demo. I also pointed out to an example that show how you could animate the text value on Android as well.

**Comment by Angelk90** [comment]
@wcandillon :  In the tutorials you do would it be possible to show the result in the Android emulator?  So there would be no other future inconveniences with other modules, I don't know if a request has already been made for you, but for those who follow your candles youtube would be very important.

**Comment by wcandillon** [comment]
@Angelk90 I have no practical way to show the android device as well yet but I definitely need to be more diligent with testing on Android.

**Comment by Angelk90** [comment]
@wcandillon : So now it works on Android too?  Can you put an expo link so I can try it?

**Comment by wcandillon** [comment]
yes here it is: https://snack.expo.io/@git/github.com/wcandillon/can-it-be-done-in-react-native:bonuses/horizontal-slider

**Comment by Angelk90** [comment]
@wcandillon :  The problem is that you don't like Android? 😂

**Comment by SynerG** [comment]
Thank you very much @wcandillon. 

Looking at the commit it's also very valuable to see what is different in Android.
In this case it looks like `Interactable` requires an `StyleSheet.absoluteFill`. And the animated text could be done manually calling `requestAnimationFrame` when required. Good to know!

You are doing a lot for the RN scene!

**Comment by McDreamy** [comment]
May I know how to set initial value for the slider?

**Comment by codemaster115** [comment]
It looks beautiful and easy to understand. Thanks for your contribution, @wcandillon 
I'm just curious how I can add onChange callback to slider so I can get updated value.
Could you please let me know how to implement it?
