### ISSUE TITLE
Instagram stories blocks touch events on the stories

### ISSUE THREAD

**Issue by cmmartin** [wcandillon/can-it-be-done-in-react-native#73]
I really like the pattern used in the Instagram Stories example where you place an empty ScrollView over top of the content and simply animate the content based on the scroll position. It's a really elegant solution to get native scroll based animations. 

However, there is an issue that I can't seem to solve: The ScrollView component overlays the visual content, instead of wrapping it, which blocks touch events to the content and prevents you from putting any buttons in the actual story. To recreate simply place a button inside the image representing the Instagram story in solution 3 to the Instagram stories problem. It will not receive any touch events.

I've tried just about everything to continue with this approach, but it seems that either the ScrollView receives the touches OR the underlying content but not both. Is there any solution to this? Or does anyone know any strategies that I can attempt?

**Comment by wcandillon** [comment]
Indeed this is a problem. If I were to redo this example today, I would use a `PanGestureHandler` from `react-native-gesture-handler` to achieve the gesture. That way it wouldn't block any touches.

**Comment by cmmartin** [comment]
Yeah, I'm going that route. It's a shame, because using the provided snapToInterval functionality without having to setup a pan responder is pretty convenient and works great aside from the touch events issue. Thanks.
