### ISSUE TITLE
Tab Bar Animation

### ISSUE THREAD

**Issue by thozh** [wcandillon/can-it-be-done-in-react-native#86]
Hello William,

I just tried to follow your react native tab bar animation challenge but I can't reproduce the same result on my phone. Is it not compatible with Android ?
Here is what I get : 
![90399552_229004811828385_8341141601992572928_n](https://user-images.githubusercontent.com/37123351/77227465-e2022a00-6b80-11ea-8e52-01f34ee350cf.png)

**Comment by wcandillon** [comment]
Thank you for letting me know, I forgot that scale=0 doesn't work on Android.
This should be fixed now :)
