### ISSUE TITLE
Difference between Android and iOS on concat

### ISSUE THREAD

**Issue by derroobin** [wcandillon/can-it-be-done-in-react-native#88]
Hello, 
I tried your custom Slider tutorial.
I tried to concat a rounded number into a textInput. On iOS i get an integer and on android it always returns a double. is there a way to concat a integer on android aswell?

**Comment by derroobin** [comment]
Ups, i was about to write an issue for reanimated aswell, guess someone else had the same problem.

https://github.com/software-mansion/react-native-reanimated/issues/677

**Comment by fxckdead** [comment]
I used `round` from `react-native-reanimated`

**Comment by derroobin** [comment]
yeah it got fix 16 days before in react native reanimated.
