### ISSUE TITLE
"Instagram stories" pinchzoom 

### ISSUE THREAD

**Issue by SmirnovM91** [wcandillon/can-it-be-done-in-react-native#89]
In this example, if something changes in parent's state(any variable's value), the component re-renders and the pinchzoom stops working.

https://github.com/wcandillon/can-it-be-done-in-react-native/tree/master/season3/src/Instagram

**Comment by wcandillon** [comment]
Yes but that's expected right? We would need to wrap the animation values in useMemoOne() to make sure that they don't loose they identity across renders. Feel free to reopen if needed.

**Comment by SmirnovM91** [comment]
Ok, thanks.
